#import '~/graphql/candidates'
#import '~/graphql/stages'

fragment FunnelFields on Funnel {
  id
  slug
  jobTitle
  description
  sla
  offerEmailTemplate
  rejectionEmailTemplate
  status
  manager {
    id
    slug
    firstName
    lastName
    nickname
  }
  candidates {
    id
  }
  offeredCandidates {
    ...CandidateFields
  }
  rejectedCandidates {
    ...CandidateFields
  }
  stages {
    ...StageFields
  }
}

mutation CreateFunnel(
  $jobTitle: String!
  $slug: String!
  $description: String
  $organizationId: ID!
  $offerEmailTemplate: String!
  $rejectionEmailTemplate: String!
  $sla: Int
  $managerId: ID!
) {
  createFunnel(
    jobTitle: $jobTitle
    slug: $slug
    description: $description
    organizationId: $organizationId
    offerEmailTemplate: $offerEmailTemplate
    rejectionEmailTemplate: $rejectionEmailTemplate
    sla: $sla
    managerId: $managerId
  ) {
    ...FunnelFields
  }
}

mutation UpdateFunnel(
  $id: ID!
  $jobTitle: String
  $description: String
  $offerEmailTemplate: String
  $rejectionEmailTemplate: String
  $sla: Int
  $managerId: ID
) {
  updateFunnel(
    id: $id
    jobTitle: $jobTitle
    description: $description
    offerEmailTemplate: $offerEmailTemplate
    rejectionEmailTemplate: $rejectionEmailTemplate
    sla: $sla
    managerId: $managerId
  ) {
    ...FunnelFields
  }
}

mutation DeleteFunnel(
  $id: ID!
) {
  deleteFunnel(
    id: $id
  ) {
    id
  }
}
