#import '~/graphql/funnels'

fragment OrganizationFields on Organization {
  id
  slug
  name
  website
  users {
    id
    slug
    firstName
    lastName
    email
    nickname
  }
  funnels {
    ...FunnelFields
  }
}

mutation CreateOrganization(
  $name: String!
  $slug: String!
  $website: String
  $usersIds: [ID!]
) {
  createOrganization(
    name: $name
    slug: $slug
    website: $website
    usersIds: $usersIds
  ) {
    ...OrganizationFields
  }
}
