#import '~/graphql/organizations'

fragment UserFields on User {
  id
  auth0UserId
  email
  slug
  firstName
  lastName
  nickname
  locale
  timeZone
  role
  organization {
    ...OrganizationFields
  }
}

query UserQuery($id: ID!) {
  user: User(id: $id) {
    ...UserFields
  }
}

mutation AuthenticateUser($accessToken: String!) {
  authenticateUser(accessToken: $accessToken) {
    id
    token
  }
}